# -*- coding: utf-8 -*-
from odoo import models, fields, api, _
from odoo.exceptions import UserError


class HksfSoTopupWizard(models.TransientModel):
    """Top-up Delivery wizard on the ORIGINAL sale order.

    Lets the user, on a confirmed rental SO, bump ordered quantities on several
    existing rental lines at once and/or add brand-new rental products. Writing
    product_uom_qty up (or creating new sale.order.line records) makes the
    native sale_stock procurement spawn the delta outgoing picking; the wizard
    then stamps the required Service Date onto those freshly created pickings so
    they are immediately billable.

    Service / erection / dismantling products (product.type == 'service', which
    live on the separate service.charge tab) are deliberately out of scope: they
    are neither listed, topped up, nor selectable here.
    """
    _name = 'hksf.so.topup.wizard'
    _description = 'SO Top-up Delivery Wizard'

    order_id = fields.Many2one(
        'sale.order',
        string='Sale Order',
        required=True,
        readonly=True,
    )
    service_date = fields.Date(
        string='Service Date',
        required=True,
        help="Scheduled (service) date stamped onto the delivery picking(s) "
             "generated by this top-up so they are billable without manual "
             "editing.",
    )
    line_ids = fields.One2many(
        'hksf.so.topup.wizard.line',
        'wizard_id',
        string='Lines',
    )

    # ------------------------------------------------------------------
    # default_get — pre-load one wizard line per eligible existing SO line
    # ------------------------------------------------------------------
    @api.model
    def default_get(self, fields_list):
        res = super().default_get(fields_list)
        active_id = self._context.get('active_id')
        if not active_id:
            return res
        order = self.env['sale.order'].browse(active_id)
        res['order_id'] = order.id
        lines = []
        for line in order.order_line.filtered(self._eligible_so_line):
            lines.append((0, 0, {
                'so_line_id': line.id,
                'product_id': line.product_id.id,
                'current_qty': line.product_uom_qty,
                'price_unit': line.price_unit,
                'product_uom_id': line.product_uom_id.id,
                'additional_qty': 0.0,
                'is_new': False,
            }))
        res['line_ids'] = lines
        return res

    @staticmethod
    def _eligible_so_line(line):
        """A line that the top-up wizard may list / top up.

        Deliverable rental stock only: a real (non section/note) line, a
        stockable/consumable product, classified as a rental line. Service
        products (erection / dismantling) are type == 'service' and excluded.
        """
        return (
            not line.display_type
            and line.product_id
            and line.product_id.type in ('product', 'consu')
            and line.line_type == 'rental'
        )

    # ------------------------------------------------------------------
    # Apply
    # ------------------------------------------------------------------
    def action_apply(self):
        self.ensure_one()
        if not self.service_date:
            raise UserError(_("Please set the Service Date before applying."))

        actionable = self.line_ids.filtered(lambda l: l.additional_qty > 0.0)
        for wline in self.line_ids:
            if wline.additional_qty < 0.0:
                raise UserError(_(
                    "Additional quantity cannot be negative (product '%s')."
                ) % (wline.product_id.display_name or ''))
            if wline.product_id and wline.product_id.type == 'service':
                raise UserError(_(
                    "Service product '%s' cannot be topped up or delivered "
                    "through this wizard. Use the Service Charges tab instead."
                ) % wline.product_id.display_name)
            if wline.is_new and wline.additional_qty > 0.0 and not wline.product_id:
                raise UserError(_("Please choose a product for each new line."))

        if not actionable:
            raise UserError(_(
                "Nothing to do: enter an Additional Quantity greater than zero "
                "on at least one line."
            ))

        order = self.order_id
        # Snapshot existing outgoing pickings for THIS order so we can isolate
        # the delta pickings procurement creates below.
        pickings_before = self._order_outgoing_pickings(order)

        period_vals = self._rental_period_vals(order)
        for wline in actionable:
            if wline.is_new or not wline.so_line_id:
                self._create_new_so_line(order, wline, period_vals)
            else:
                so_line = wline.so_line_id
                so_line.product_uom_qty = so_line.product_uom_qty + wline.additional_qty

        # Native sale_stock procurement runs on write/create above and spawns
        # the delta picking(s). Stamp the Service Date onto the new ones.
        self._stamp_new_pickings(order, pickings_before)

        return {'type': 'ir.actions.act_window_close'}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _order_outgoing_pickings(self, order):
        return self.env['stock.picking'].search([
            ('sale_id', '=', order.id),
            ('picking_type_code', '=', 'outgoing'),
        ])

    def _rental_period_vals(self, order):
        """Rental period defaults copied to NEW lines so quotation-level
        pricing (price_unit × month) is correct. Sourced from an existing
        rental line on the order; falls back to the order's sale type only."""
        template = order.order_line.filtered(self._eligible_so_line)[:1]
        vals = {'custom_sale_type': order.custom_sale_type}
        if template:
            vals.update({
                'start_date': template.start_date,
                'end_date': template.end_date,
                'month': template.month,
                'custom_days': template.custom_days,
                'custom_month': template.custom_month,
            })
        return vals

    def _create_new_so_line(self, order, wline, period_vals):
        if not wline.product_id:
            raise UserError(_("Please choose a product for each new line."))
        if wline.product_id.type == 'service':
            raise UserError(_(
                "Service product '%s' cannot be added here."
            ) % wline.product_id.display_name)
        vals = {
            'order_id': order.id,
            'product_id': wline.product_id.id,
            'product_uom_qty': wline.additional_qty,
            'line_type': 'rental',
        }
        # Copy the rental period so pricing matches the rest of the order. Only
        # set fields that are writable (custom_days/custom_month are computed).
        if period_vals.get('start_date'):
            vals['start_date'] = period_vals['start_date']
        if period_vals.get('end_date'):
            vals['end_date'] = period_vals['end_date']
        if period_vals.get('month'):
            vals['month'] = period_vals['month']
        # Let the module's pricing logic compute price_unit from the product;
        # do NOT hardcode a price.
        self.env['sale.order.line'].create(vals)

    def _stamp_new_pickings(self, order, pickings_before):
        """Stamp service_date onto the delta outgoing pickings just created for
        THIS order. Robust: only pickings on this order, only outgoing, only
        those still lacking a scheduled_date_only (so we never overwrite a date
        a user already set on an older picking)."""
        new_pickings = self._order_outgoing_pickings(order) - pickings_before
        to_stamp = new_pickings.filtered(lambda p: not p.scheduled_date_only)
        if to_stamp:
            to_stamp.write({'scheduled_date_only': self.service_date})


class HksfSoTopupWizardLine(models.TransientModel):
    _name = 'hksf.so.topup.wizard.line'
    _description = 'SO Top-up Delivery Wizard Line'

    wizard_id = fields.Many2one(
        'hksf.so.topup.wizard',
        string='Wizard',
        required=True,
        ondelete='cascade',
    )
    so_line_id = fields.Many2one(
        'sale.order.line',
        string='Sale Line',
    )
    product_id = fields.Many2one(
        'product.product',
        string='Product',
        domain="[('type', 'in', ('product', 'consu'))]",
    )
    is_new = fields.Boolean(
        string='New Product',
        default=False,
        help="True when this row adds a product not currently on the order.",
    )
    current_qty = fields.Float(
        string='Current Ordered Qty',
        digits='Product Unit of Measure',
        readonly=True,
    )
    price_unit = fields.Float(
        string='Unit Price',
        digits='Product Price',
        readonly=True,
    )
    product_uom_id = fields.Many2one(
        'uom.uom',
        string='Unit of Measure',
        readonly=True,
    )
    additional_qty = fields.Float(
        string='Additional Qty',
        digits='Product Unit of Measure',
        default=0.0,
    )
    new_total_qty = fields.Float(
        string='New Total Qty',
        digits='Product Unit of Measure',
        compute='_compute_new_total_qty',
    )

    @api.depends('current_qty', 'additional_qty')
    def _compute_new_total_qty(self):
        for line in self:
            line.new_total_qty = (line.current_qty or 0.0) + (line.additional_qty or 0.0)

    @api.onchange('product_id')
    def _onchange_product_id(self):
        """If the chosen product already matches an eligible existing SO line on
        this order, auto-fill its current qty / price / uom and mark it as an
        existing top-up; otherwise treat it as a new product line."""
        if not self.product_id:
            self.is_new = False
            self.so_line_id = False
            self.current_qty = 0.0
            return
        if self.product_id.type == 'service':
            self.product_id = False
            return {'warning': {
                'title': _("Service product not allowed"),
                'message': _(
                    "Service / erection / dismantling products cannot be "
                    "topped up or delivered through this wizard."
                ),
            }}
        order = self.wizard_id.order_id
        match = order.order_line.filtered(
            lambda l: HksfSoTopupWizard._eligible_so_line(l)
            and l.product_id == self.product_id
        )[:1]
        if match:
            self.so_line_id = match.id
            self.current_qty = match.product_uom_qty
            self.price_unit = match.price_unit
            self.product_uom_id = match.product_uom_id.id
            self.is_new = False
        else:
            self.so_line_id = False
            self.current_qty = 0.0
            self.price_unit = self.product_id.lst_price
            self.product_uom_id = self.product_id.uom_id.id
            self.is_new = True

    @api.constrains('additional_qty')
    def _check_additional_qty(self):
        for line in self:
            if line.additional_qty < 0.0:
                raise UserError(_("Additional quantity cannot be negative."))
